/* 1. XÓA DỮ LIỆU CŨ */
DELETE FROM AIHairTryOns;
DELETE FROM AIHairStyles;
DBCC CHECKIDENT ('AIHairStyles', RESEED, 0);

/* 2. CHÈN 36 KIỂU TÓC MỚI */
INSERT INTO AIHairStyles (StyleCode, StyleName, StyleType, HairLength, HairTexture, MaintenanceLevel, Description, ThumbnailUrl, ServiceId, Audience, PromptVersion, IsActive, SortOrder, PromptTemplate) VALUES
-- NAM (ServiceId = 3)
('UNDERCUT_MALE', N'Undercut', 'CUT', 'SHORT', N'STRAIGHT', 'MEDIUM', N'Cắt ngắn hoặc cạo hai bên và phía sau, phần tóc trên đỉnh đầu để dài hơn để vuốt ngược hoặc tạo kiểu.', '/images/hairstyles/undercut-male.jpg', 3, 'MALE', 'v3', 1, 1, 'ultra-detailed undercut hairstyle, short faded sides, longer slicked back top, masculine hair texture, photorealistic individual hair strands, cinematic salon lighting, 8k resolution, perfectly blended hairline'),
('POMPADOUR_MALE', N'Pompadour', 'CUT', 'MEDIUM', N'STRAIGHT', 'HIGH', N'Phần tóc mái được vuốt ngược và tạo độ phồng lớn, mang lại vẻ lịch lãm, cổ điển.', '/images/hairstyles/pompadour-male.jpg', 3, 'MALE', 'v3', 1, 2, 'ultra-detailed classic pompadour hairstyle, high volume slicked back front, tight faded sides, realistic shiny hair texture, photorealistic individual hair strands, cinematic salon lighting, 8k resolution'),
('QUIFF_MALE', N'Quiff', 'CUT', 'MEDIUM', N'WAVY', 'HIGH', N'Gần giống Pompadour nhưng phần mái vuốt hắt lên trên và hơi hướng về phía trước, trẻ trung hơn.', '/images/hairstyles/quiff-male.jpg', 3, 'MALE', 'v3', 1, 3, 'ultra-detailed modern textured quiff hairstyle, hair swept upwards and forwards, textured wavy volume, photorealistic individual hair strands, cinematic salon lighting, 8k resolution, perfectly blended hairline'),
('SIDEPART_MALE', N'Side Part', 'CUT', 'SHORT', N'STRAIGHT', 'MEDIUM', N'Tóc được chia ngôi lệch (7/3 hoặc 8/2), chải chuốt gọn gàng, phù hợp với môi trường công sở.', '/images/hairstyles/sidepart-male.jpg', 3, 'MALE', 'v3', 1, 4, 'ultra-detailed classic side part hairstyle, deep parting line, combed neat hair, professional masculine style, photorealistic individual hair strands, cinematic salon lighting, 8k resolution'),
('TWOBLOCK_MALE', N'Two Block', 'CUT', 'MEDIUM', N'WAVY', 'LOW', N'Kiểu tóc Hàn Quốc với phần đỉnh đầu để dài, uốn nhẹ hoặc tỉa layer, hai bên và gáy cắt gọn.', '/images/hairstyles/twoblock-male.jpg', 3, 'MALE', 'v3', 1, 5, 'ultra-detailed korean two block haircut, disconnected undercut, long textured slightly wavy top, soft masculine look, photorealistic individual hair strands, cinematic salon lighting, 8k resolution'),
('MULLET_MALE', N'Mullet', 'CUT', 'LONG', N'STRAIGHT', 'LOW', N'Hai bên cắt ngắn nhưng phần tóc gáy để dài chạm hoặc qua cổ.', '/images/hairstyles/mullet-male.jpg', 3, 'MALE', 'v3', 1, 6, 'ultra-detailed modern mullet hairstyle, short sides, long flowing back hair, textured top, photorealistic individual hair strands, cinematic salon lighting, 8k resolution, perfectly blended hairline'),
('BUZZCUT_MALE', N'Buzz Cut', 'CUT', 'SHORT', N'STRAIGHT', 'LOW', N'Tóc được cạo rất ngắn và đều sát da đầu, mát mẻ và nam tính.', '/images/hairstyles/buzzcut-male.jpg', 3, 'MALE', 'v3', 1, 7, 'ultra-detailed buzz cut, very short clipped hair all over, even fade, masculine military style, photorealistic scalp texture, cinematic salon lighting, 8k resolution'),
('CREWCUT_MALE', N'Crew Cut', 'CUT', 'SHORT', N'STRAIGHT', 'LOW', N'Phiên bản dài hơn của Buzz Cut một chút, phần đỉnh đầu dài hơn hai bên và gáy.', '/images/hairstyles/crewcut-male.jpg', 3, 'MALE', 'v3', 1, 8, 'ultra-detailed crew cut hairstyle, slightly longer front, tapered sides and back, textured top, photorealistic individual hair strands, cinematic salon lighting, 8k resolution'),
('FRENCHCROP_MALE', N'French Crop', 'CUT', 'SHORT', N'STRAIGHT', 'LOW', N'Hai bên cắt sát, phần tóc trên đỉnh để ngắn và mái được tỉa ngang hoặc rủ xuống trán.', '/images/hairstyles/frenchcrop-male.jpg', 3, 'MALE', 'v3', 1, 9, 'ultra-detailed french crop haircut, tight skin fade on sides, textured short fringe swept forward, photorealistic individual hair strands, cinematic salon lighting, 8k resolution'),
('SLICKEDBACK_MALE', N'Slicked Back', 'CUT', 'MEDIUM', N'STRAIGHT', 'HIGH', N'Toàn bộ tóc được vuốt ép sát ra sau bằng pomade hoặc gel bóng.', '/images/hairstyles/slickedback-male.jpg', 3, 'MALE', 'v3', 1, 10, 'ultra-detailed slicked back hairstyle, medium length hair combed straight back with pomade, shiny wet hair texture, photorealistic individual hair strands, cinematic salon lighting, 8k resolution'),
('MOHICAN_MALE', N'Mohican', 'CUT', 'MEDIUM', N'STRAIGHT', 'HIGH', N'Hai bên cạo sát, phần tóc từ trán kéo dài xuống gáy được để dài hơn và thường vuốt chụm lại.', '/images/hairstyles/mohican-male.jpg', 3, 'MALE', 'v3', 1, 11, 'ultra-detailed modern mohawk mohican hairstyle, shaved sides, long spiked strip of hair down the center, photorealistic individual hair strands, cinematic salon lighting, 8k resolution'),
('IVYLEAGUE_MALE', N'Ivy League', 'CUT', 'SHORT', N'STRAIGHT', 'LOW', N'Sự kết hợp giữa Crew Cut và Side Part, phần mái đủ dài để vuốt rẽ ngôi nhẹ.', '/images/hairstyles/ivyleague-male.jpg', 3, 'MALE', 'v3', 1, 12, 'ultra-detailed ivy league haircut, smart casual style, side parted short hair, neat taper, photorealistic individual hair strands, cinematic salon lighting, 8k resolution'),
('LAYER_MALE', N'Layer Nam', 'CUT', 'MEDIUM', N'WAVY', 'MEDIUM', N'Tóc được cắt tỉa thành nhiều tầng đan xen, tạo độ phồng và tự nhiên.', '/images/hairstyles/layer-male.jpg', 3, 'MALE', 'v3', 1, 13, 'ultra-detailed men layered haircut, messy textured layers, natural flow, soft wavy volume, photorealistic individual hair strands, cinematic salon lighting, 8k resolution'),
('FAUXHAWK_MALE', N'Faux Hawk', 'CUT', 'SHORT', N'STRAIGHT', 'HIGH', N'Tương tự Mohican nhưng phần đỉnh không vuốt quá sắc nhọn, hai bên không cạo quá sát.', '/images/hairstyles/fauxhawk-male.jpg', 3, 'MALE', 'v3', 1, 14, 'ultra-detailed faux hawk haircut, faded sides, textured hair pushed towards the center, photorealistic individual hair strands, cinematic salon lighting, 8k resolution'),
('TEXTUREDFRINGE_MALE', N'Textured Fringe', 'CUT', 'MEDIUM', N'WAVY', 'MEDIUM', N'Tóc mái để rủ xuống nhưng được tỉa lộn xộn có chủ đích, tạo hiệu ứng đan xen.', '/images/hairstyles/texturedfringe-male.jpg', 3, 'MALE', 'v3', 1, 15, 'ultra-detailed textured fringe haircut, heavy messy front bangs, choppy textured layers, photorealistic individual hair strands, cinematic salon lighting, 8k resolution'),
('SHORTQUIFF_MALE', N'Short Quiff', 'CUT', 'SHORT', N'WAVY', 'LOW', N'Quiff nhưng với độ dài tóc ngắn hơn, dễ vuốt và không mất nhiều thời gian chăm sóc.', '/images/hairstyles/shortquiff-male.jpg', 3, 'MALE', 'v3', 1, 16, 'ultra-detailed short quiff hairstyle, short hair brushed up at the front, low maintenance texture, photorealistic individual hair strands, cinematic salon lighting, 8k resolution'),
('CAESARCUT_MALE', N'Caesar Cut', 'CUT', 'SHORT', N'STRAIGHT', 'LOW', N'Tóc cắt ngắn sát với phần mái được tỉa bằng và chải rủ xuống trán.', '/images/hairstyles/caesarcut-male.jpg', 3, 'MALE', 'v3', 1, 17, 'ultra-detailed caesar cut, short even horizontal fringe, tight faded sides, photorealistic individual hair strands, cinematic salon lighting, 8k resolution'),
('DREADLOCKS_MALE', N'Dreadlocks', 'TEXTURE', 'LONG', N'CURLY', 'HIGH', N'Kiểu tóc cá tính mang phong cách Hip-hop, tóc được tết thành từng lọn bết chặt vào nhau.', '/images/hairstyles/dreadlocks-male.jpg', 3, 'MALE', 'v3', 1, 18, 'ultra-detailed mens dreadlocks hairstyle, thick textured locs, roots and twists, photorealistic individual hair strands, cinematic salon lighting, 8k resolution'),

-- NỮ (ServiceId = 4)
('BOB_FEMALE', N'Tóc Bob', 'CUT', 'SHORT', N'STRAIGHT', 'LOW', N'Tóc cắt ngắn ngang xương hàm hoặc ngang cằm, có thể duỗi thẳng, uốn cụp hoặc làm xoăn nhẹ.', '/images/hairstyles/bob-female.jpg', 4, 'FEMALE', 'v3', 1, 19, 'ultra-detailed short bob haircut, chin-length straight hair, blunt ends, sleek and elegant, photorealistic individual hair strands, cinematic salon lighting, 8k resolution, perfectly blended hairline'),
('LOB_FEMALE', N'Tóc Lob', 'CUT', 'MEDIUM', N'STRAIGHT', 'LOW', N'Phiên bản dài hơn của tóc Bob, thường dài đến ngang vai.', '/images/hairstyles/lob-female.jpg', 4, 'FEMALE', 'v3', 1, 20, 'ultra-detailed lob long bob haircut, shoulder length straight hair, soft texture, photorealistic individual hair strands, cinematic salon lighting, 8k resolution'),
('PIXIE_FEMALE', N'Pixie', 'CUT', 'SHORT', N'STRAIGHT', 'LOW', N'Cắt rất ngắn sát gáy và hai bên, phần mái có thể để lệch hoặc uốn nhẹ, cực kỳ cá tính.', '/images/hairstyles/pixie-female.jpg', 4, 'FEMALE', 'v3', 1, 21, 'ultra-detailed pixie cut hairstyle, very short feminine hair, soft tapered nape, textured top, photorealistic individual hair strands, cinematic salon lighting, 8k resolution'),
('LAYER_FEMALE', N'Tóc Layer', 'CUT', 'LONG', N'STRAIGHT', 'MEDIUM', N'Tóc được tỉa so le thành nhiều lớp, giúp tóc trông bồng bềnh và ôm sát khuôn mặt.', '/images/hairstyles/layer-female.jpg', 4, 'FEMALE', 'v3', 1, 22, 'ultra-detailed long layered haircut, cascading soft layers framing the face, voluminous flow, photorealistic individual hair strands, cinematic salon lighting, 8k resolution'),
('BUTTERFLY_FEMALE', N'Butterfly Cut', 'CUT', 'LONG', N'WAVY', 'HIGH', N'Tóc layer với các lớp tóc ngắn ôm mặt và các lớp dài xõa bung ra sau, tạo hiệu ứng như cánh bướm.', '/images/hairstyles/butterfly-female.jpg', 4, 'FEMALE', 'v3', 1, 23, 'ultra-detailed butterfly haircut, feathery face-framing layers, long voluminous wings of hair, highly textured, photorealistic individual hair strands, cinematic salon lighting, 8k resolution'),
('HIME_FEMALE', N'Hime Cut', 'CUT', 'LONG', N'STRAIGHT', 'HIGH', N'Tóc dài thẳng với hai lọn tóc mai phía trước được cắt bằng ngang má hoặc cằm.', '/images/hairstyles/hime-female.jpg', 4, 'FEMALE', 'v3', 1, 24, 'ultra-detailed hime cut hairstyle, straight long back hair, blunt cheek-length sidelocks, sharp precise cuts, photorealistic individual hair strands, cinematic salon lighting, 8k resolution'),
('WOLF_FEMALE', N'Wolf Cut', 'CUT', 'MEDIUM', N'WAVY', 'MEDIUM', N'Sự pha trộn giữa Mullet và Shag, tóc được tỉa xù xù lộn xộn bồng bềnh, phần gáy để dài.', '/images/hairstyles/wolf-female.jpg', 4, 'FEMALE', 'v3', 1, 25, 'ultra-detailed wolf cut hairstyle, messy shaggy layers, heavy fringe, longer back, rebellious feminine look, photorealistic individual hair strands, cinematic salon lighting, 8k resolution'),
('SHAG_FEMALE', N'Shag Cut', 'CUT', 'MEDIUM', N'WAVY', 'MEDIUM', N'Kiểu tóc tỉa layer nhiều lớp một cách ngẫu hứng, tạo vẻ ngoài hơi rối và phóng khoáng.', '/images/hairstyles/shag-female.jpg', 4, 'FEMALE', 'v3', 1, 26, 'ultra-detailed shag haircut, heavily textured choppy layers, effortless messy waves, rock and roll vibe, photorealistic individual hair strands, cinematic salon lighting, 8k resolution'),
('WAVY_FEMALE', N'Uốn Sóng Nước', 'TEXTURE', 'LONG', N'WAVY', 'HIGH', N'Tóc dài được uốn xoăn nhẹ nhàng, tạo thành các lọn sóng bồng bềnh và tự nhiên.', '/images/hairstyles/wavy-female.jpg', 4, 'FEMALE', 'v3', 1, 27, 'ultra-detailed long wavy hair, soft natural flowing beach waves, luminous shine, photorealistic individual hair strands, cinematic salon lighting, 8k resolution'),
('HIPPIE_FEMALE', N'Xoăn Hippie', 'TEXTURE', 'LONG', N'CURLY', 'HIGH', N'Tóc được uốn xoăn tít từ chân đến ngọn, mang đậm phong cách vintage và nghệ thuật.', '/images/hairstyles/hippie-female.jpg', 4, 'FEMALE', 'v3', 1, 28, 'ultra-detailed hippie curly hair, tight vintage curls from root to tip, extreme volume, wild texture, photorealistic individual hair strands, cinematic salon lighting, 8k resolution'),
('CURTAINBANGS_FEMALE', N'Mái Bay', 'CUT', 'MEDIUM', N'WAVY', 'MEDIUM', N'Tóc mái được chia đôi và cắt uốn lơi sang hai bên, ôm nhẹ vào gò má.', '/images/hairstyles/curtainbangs-female.jpg', 4, 'FEMALE', 'v3', 1, 29, 'ultra-detailed long hair with curtain bangs, soft sweeping parted fringe framing the face, photorealistic individual hair strands, cinematic salon lighting, 8k resolution'),
('WISPYBANGS_FEMALE', N'Mái Thưa', 'CUT', 'MEDIUM', N'STRAIGHT', 'MEDIUM', N'Tóc mái cắt mỏng, lơ thơ trước trán theo phong cách Hàn Quốc.', '/images/hairstyles/wispybangs-female.jpg', 4, 'FEMALE', 'v3', 1, 30, 'ultra-detailed korean wispy bangs, see-through thin fringe, straight elegant hair, photorealistic individual hair strands, cinematic salon lighting, 8k resolution'),
('STRAIGHT_FEMALE', N'Duỗi Thẳng', 'TEXTURE', 'LONG', N'STRAIGHT', 'LOW', N'Tóc để dài và duỗi thẳng mượt, không bao giờ lỗi mốt.', '/images/hairstyles/straight-female.jpg', 4, 'FEMALE', 'v3', 1, 31, 'ultra-detailed pin straight long hair, glass hair, ultra smooth and silky texture, highly reflective, photorealistic individual hair strands, cinematic salon lighting, 8k resolution'),
('CCURL_FEMALE', N'Cụp Chữ C', 'TEXTURE', 'MEDIUM', N'STRAIGHT', 'MEDIUM', N'Phần đuôi tóc uốn cụp nhẹ vào trong (hình chữ C), mang lại vẻ thanh lịch và nữ tính.', '/images/hairstyles/ccurl-female.jpg', 4, 'FEMALE', 'v3', 1, 32, 'ultra-detailed medium length hair with c-curl ends, ends smoothly curled inward, elegant volume, photorealistic individual hair strands, cinematic salon lighting, 8k resolution'),
('BIGCURLS_FEMALE', N'Xoăn Lọn To', 'TEXTURE', 'LONG', N'WAVY', 'HIGH', N'Tóc dài uốn xoăn ở phần đuôi với các lọn to, quyến rũ và phù hợp cho các dịp sang trọng.', '/images/hairstyles/bigcurls-female.jpg', 4, 'FEMALE', 'v3', 1, 33, 'ultra-detailed glamorous big bouncy curls, thick heavy curled ends, luxurious salon blow-out, photorealistic individual hair strands, cinematic salon lighting, 8k resolution'),
('LOOSECURLS_FEMALE', N'Uốn Lơi', 'TEXTURE', 'LONG', N'WAVY', 'MEDIUM', N'Các lọn tóc xoăn rất nhẹ, nhìn như chỉ hơi gợn sóng, cực kỳ tự nhiên.', '/images/hairstyles/loosecurls-female.jpg', 4, 'FEMALE', 'v3', 1, 34, 'ultra-detailed loose curls hairstyle, subtle natural barely-there waves, effortless beauty, photorealistic individual hair strands, cinematic salon lighting, 8k resolution'),
('FLIPPEDENDS_FEMALE', N'Uốn Vểnh', 'TEXTURE', 'MEDIUM', N'WAVY', 'MEDIUM', N'Tóc cắt ngang vai và phần đuôi được uốn vểnh nhẹ ra ngoài thay vì uốn cụp vào trong.', '/images/hairstyles/flippedends-female.jpg', 4, 'FEMALE', 'v3', 1, 35, 'ultra-detailed shoulder length hair with flipped out ends, retro flipped ends, playful texture, photorealistic individual hair strands, cinematic salon lighting, 8k resolution'),
('MULLET_FEMALE', N'Mullet Nữ', 'CUT', 'MEDIUM', N'WAVY', 'MEDIUM', N'Tương tự mullet nam nhưng được tỉa mềm mại hơn, ôm sát khuôn mặt và tạo vẻ cool ngầu.', '/images/hairstyles/mullet-female.jpg', 4, 'FEMALE', 'v3', 1, 36, 'ultra-detailed feminine mullet, soft shaggy short top, wispy longer back, edgy alternative look, photorealistic individual hair strands, cinematic salon lighting, 8k resolution');
