/* 3. BỔ SUNG CÁC MẪU MÀU TÓC (COLOR) */
INSERT INTO AIHairStyles (StyleCode, StyleName, StyleType, HairLength, HairTexture, MaintenanceLevel, Description, PromptTemplate, ThumbnailUrl, AccentColor, ServiceId, Audience, IsTrending, TrendScore, SortOrder)
VALUES 
-- MÀU TÓC NỮ
('COLOR_ASH_BROWN', N'Nâu Khói (Ash Brown)', 'COLOR', 'MEDIUM', 'STRAIGHT', 'HIGH', N'Màu nâu lạnh ánh khói sành điệu, tôn da trắng.', 'ash brown hair, silver brown hair color, cool tone brown hair, (detailed hair texture:1.2), salon quality, highly detailed hair', '/images/hairstyles/color-ash-brown.jpg', '#8b7e7a', NULL, 'FEMALE', 1, 95, 100),
('COLOR_PLATINUM_BLONDE', N'Bạch Kim (Platinum Blonde)', 'COLOR', 'MEDIUM', 'STRAIGHT', 'HIGH', N'Màu bạch kim cá tính, nổi bật.', 'platinum blonde hair, icy blonde, white blonde hair, (detailed hair texture:1.2), salon quality, highly detailed hair', '/images/hairstyles/color-platinum.jpg', '#e5e4e2', NULL, 'FEMALE', 1, 90, 101),
('COLOR_CHOCOLATE', N'Nâu Socola (Chocolate)', 'COLOR', 'MEDIUM', 'STRAIGHT', 'LOW', N'Màu nâu trầm ấm áp, tự nhiên, phù hợp mọi màu da.', 'chocolate brown hair, rich dark brown hair, warm brown hair color, (detailed hair texture:1.2), salon quality', '/images/hairstyles/color-chocolate.jpg', '#5d3c2e', NULL, 'FEMALE', 1, 98, 102),
('COLOR_CHESTNUT', N'Nâu Hạt Dẻ (Chestnut)', 'COLOR', 'MEDIUM', 'STRAIGHT', 'LOW', N'Màu nâu sáng ấm, trẻ trung và thanh lịch.', 'chestnut brown hair, warm light brown hair, reddish brown undertones, (detailed hair texture:1.2), salon quality', '/images/hairstyles/color-chestnut.jpg', '#954535', NULL, 'FEMALE', 1, 85, 103),
('COLOR_BALAYAGE', N'Nhuộm Balayage', 'COLOR', 'MEDIUM', 'STRAIGHT', 'MEDIUM', N'Kỹ thuật nhuộm chuyển màu mềm mại, tạo chiều sâu cho tóc.', 'balayage hair coloring, highlights, gradient hair color, brown to blonde balayage, (detailed hair texture:1.2), salon quality', '/images/hairstyles/color-balayage.jpg', '#d4af37', NULL, 'FEMALE', 1, 99, 104),
('COLOR_HIDDEN', N'Nhuộm Hidden (Hidden Color)', 'COLOR', 'MEDIUM', 'STRAIGHT', 'MEDIUM', N'Nhuộm giấu màu tinh tế bên trong lớp tóc.', 'hidden hair color, inner hair dyed bright color, peekaboo hair color, black hair with hidden blue or pink, (detailed hair texture:1.2), salon quality', '/images/hairstyles/color-hidden.jpg', '#ff1493', NULL, 'FEMALE', 1, 88, 105),

-- MÀU TÓC NAM
('COLOR_ASH_GREY_MALE', N'Xám Khói (Ash Grey)', 'COLOR', 'SHORT', 'STRAIGHT', 'HIGH', N'Màu xám khói cực chất và nam tính.', 'ash grey hair, silver grey hair male, cool tone grey hair, (detailed hair texture:1.2), salon quality', '/images/hairstyles/color-ash-grey-male.jpg', '#808080', NULL, 'MALE', 1, 92, 106),
('COLOR_COPPER_BROWN_MALE', N'Nâu Đồng (Copper Brown)', 'COLOR', 'SHORT', 'STRAIGHT', 'LOW', N'Màu nâu ánh đồng sáng, giúp khuôn mặt sáng hơn.', 'copper brown hair, warm orange brown hair male, (detailed hair texture:1.2), salon quality', '/images/hairstyles/color-copper-male.jpg', '#b87333', NULL, 'MALE', 1, 85, 107),
('COLOR_BLUE_BLACK_MALE', N'Xanh Đen (Blue Black)', 'COLOR', 'SHORT', 'STRAIGHT', 'MEDIUM', N'Màu đen tuyền có ánh xanh dương khi ra nắng.', 'blue black hair, dark hair with blue reflection male, (detailed hair texture:1.2), salon quality', '/images/hairstyles/color-blue-black-male.jpg', '#00008b', NULL, 'MALE', 1, 90, 108),
('COLOR_RED_WINE_MALE', N'Đỏ Rượu (Red Wine)', 'COLOR', 'SHORT', 'STRAIGHT', 'MEDIUM', N'Màu đỏ rượu vang sành điệu.', 'red wine hair color, burgundy hair male, dark red hair, (detailed hair texture:1.2), salon quality', '/images/hairstyles/color-red-wine-male.jpg', '#722f37', NULL, 'MALE', 1, 80, 109);
